[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-flowise"
version = "0.1.0"
description = "MCP integration with the Flowise API for creating predictions and managing chatflows/assistants"
readme = "README.md"
authors = [
  { name = "Matthew Hand", email = "andydukesau@gmail.com" }
]
dependencies = [
  "mcp[cli]>=1.2.0",
  "pytest>=8.3.4",
  "python-dotenv>=1.0.1",
  "requests>=2.25.0",
]

[project.scripts]
mcp-flowise = "mcp_flowise.__main__:main"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]

[tool.setuptools.packages]
find = {include = ["mcp_flowise", "mcp_flowise.*"]}
