name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install uv
      - name: Install uv
        run: pip install uvicorn astral-sh uv-cli pytest

      # Sync dependencies with uv
      - name: Install dependencies
        run: uv sync --all-extras --dev

      # Run tests
      - name: Run tests
        run: uv run pytest tests/unit
        env:
          PYTHONPATH: ${{ github.workspace }}
